### ISSUE TITLE
Process - How to run test suite locally

### ISSUE THREAD

**Issue by Maquidos** [ITU-BDSA23-GROUP12/Chirp#368]
_List all necessary steps that Rasmus or Helge have to perform to execute your test suites. Here, you can assume that we already cloned your repository in the step above._

_Briefly describe what kinds of tests you have in your test suites and what they are testing._

**Comment by palleBrandt** [comment]
Should we guide them to the command of running our integration tests? Because if you run the UI test from a new computer you need to verify the login BDSATester user with an emailcode? Maybe thats too tought, and we keep that just like something we run locally during development? Then of cause explain why they cant test it.
